/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANKIT
 */
public class ApproveLeaveFrame extends javax.swing.JFrame {

    private String eid;
    
    /** Creates new form ApproveLeaveFrame */
    public ApproveLeaveFrame() {
        initComponents();
        this.setResizable(false);
    }
    public ApproveLeaveFrame(String eid) {
        initComponents();
        this.setResizable(false);
        this.eid=eid;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        leave_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        refreshBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        disaproveBtn = new javax.swing.JButton();

        leave_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "eid", "no of days", "subject", "content", "timestamp", "approval"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(leave_table);
        if (leave_table.getColumnModel().getColumnCount() > 0) {
            leave_table.getColumnModel().getColumn(0).setResizable(false);
            leave_table.getColumnModel().getColumn(1).setResizable(false);
            leave_table.getColumnModel().getColumn(2).setResizable(false);
            leave_table.getColumnModel().getColumn(3).setResizable(false);
            leave_table.getColumnModel().getColumn(4).setResizable(false);
            leave_table.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Leave Approval");

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        disaproveBtn.setText("Disapprove");
        disaproveBtn.setToolTipText("");
        disaproveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disaproveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(refreshBtn)
                .addGap(30, 30, 30)
                .addComponent(approveBtn)
                .addGap(30, 30, 30)
                .addComponent(disaproveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshBtn)
                    .addComponent(approveBtn)
                    .addComponent(disaproveBtn))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        DefaultTableModel model1 = new DefaultTableModel(new String[]{"EID","No of days","Subject","Content","Timestamp","Approval"}, 0);
        leave_table.setModel(model1);
        

        int noOfDays;
        String subj,msg,approval,ts,eid;
        try {
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hr", "root", "");
            Statement stmt=con.createStatement();
            String sql="select * from leave_applications where approval='pending' ";
            ResultSet rs=stmt.executeQuery(sql);
            
            while(rs.next()){
                eid=rs.getString("eid");
                noOfDays=rs.getInt("no_of_days");
                subj=rs.getString("leave_sub");
                msg=rs.getString("leave_content");
                ts=rs.getString("timestamp");
                approval=rs.getString("approval");
                model1.addRow(new Object[]{eid,noOfDays,subj,msg,ts,approval});
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("ERROR");
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        int column=0;
        int row=leave_table.getSelectedRow();
        String eid_lt=leave_table.getModel().getValueAt(row, column).toString();
        String ts_lt=leave_table.getModel().getValueAt(row, 4).toString();
        
        System.out.println(eid_lt+" "+ts_lt);
        
        ApproveLeave al=new ApproveLeave();
        
        int status1=al.getLeaves(eid_lt);
        int status2=al.getLeavesApplications(eid_lt);
        int status3=al.calculations(eid_lt);
        int status=al.approveStatus(eid_lt, ts_lt);
        
        
        
        if(status==1 && status2==1 && status3==1){
            
            JOptionPane.showMessageDialog(null, "Status set to Approved", "STATUS", JOptionPane.PLAIN_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(null, "Setting status failed", "STATUS", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_approveBtnActionPerformed

    private void disaproveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disaproveBtnActionPerformed
        int column=0;
        int row=leave_table.getSelectedRow();
        String eid_lt=leave_table.getModel().getValueAt(row, column).toString();
        String ts_lt=leave_table.getModel().getValueAt(row, 4).toString();
        
        System.out.println(eid_lt+" "+ts_lt);
        
        DisapproveLeave dl=new DisapproveLeave();
        int status=dl.disapproveStatus(eid_lt, ts_lt);
    }//GEN-LAST:event_disaproveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApproveLeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApproveLeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApproveLeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApproveLeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApproveLeaveFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton disaproveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable leave_table;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables

}
