/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;

import hrmanagement.*;
import Emp.LeaveMgmt;
import Login.LoginPage;
import Project.AssignProjectFrame;
import Project.ProjectStatusFrame;

/**
 *
 * @author ANKIT
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form HRMgmt
     */
    private String eid;
    
    public Manager() {
        initComponents();
        this.setResizable(false);
    }
    public Manager(String eid) {
        initComponents();
        this.setResizable(false);
        
        
        this.eid=eid;
        
        LeaveMgmt lm=new LeaveMgmt();
        lm.displayInfo(eid);
        eidlbl.setText(lm.getEid());
        namelbl.setText(lm.getEname());
        emaillbl.setText(lm.getEmail());
        mobilelbl.setText(Long.toString(lm.getPhno()));
        addrlbl.setText(lm.getStreet()+", "+lm.getCity()+", "+lm.getState()+", "+lm.getCountry());

    }
    
    public Manager(String eid,boolean isExecutive) {
        initComponents();
        this.setResizable(false);
        titleLbl.setText("Executive Portal");
        
        this.eid=eid;
        
        LeaveMgmt lm=new LeaveMgmt();
        lm.displayInfo(eid);
        eidlbl.setText(lm.getEid());
        namelbl.setText(lm.getEname());
        emaillbl.setText(lm.getEmail());
        mobilelbl.setText(Long.toString(lm.getPhno()));
        addrlbl.setText(lm.getStreet()+", "+lm.getCity()+", "+lm.getState()+", "+lm.getCountry());
        
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        approveLeavelbl = new javax.swing.JButton();
        addEmp = new javax.swing.JButton();
        viewRecBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        eidlbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        mobilelbl = new javax.swing.JLabel();
        addrlbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        logoutBtn = new javax.swing.JButton();
        idComboBox = new javax.swing.JComboBox<>();
        updateID = new javax.swing.JButton();
        salaryBtn = new javax.swing.JButton();
        leaveBtn = new javax.swing.JButton();
        assignPrjBtn = new javax.swing.JButton();
        viewProjBtn = new javax.swing.JButton();
        viewProjBtn1 = new javax.swing.JButton();

        setTitle("Management Control Panel");

        approveLeavelbl.setText("Approve Leave");
        approveLeavelbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveLeavelblActionPerformed(evt);
            }
        });

        addEmp.setText("Create ID");
        addEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpActionPerformed(evt);
            }
        });

        viewRecBtn.setText("View Records");
        viewRecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Manager Portal");

        eidlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eidlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eidlbl.setText("jLabel1");

        namelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namelbl.setText("jLabel1");

        emaillbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emaillbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emaillbl.setText("jLabel1");

        mobilelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mobilelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mobilelbl.setText("jLabel1");

        addrlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addrlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addrlbl.setText("jLabel1");

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl1.setText("Employee ID:");

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl3.setText("E-mail:");

        lbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl4.setText("Mobile no:");

        lbl5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl5.setText("Address:");

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl2.setText("Name:");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        idComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Manager", "Executive" }));

        updateID.setText("Update ID");
        updateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateIDActionPerformed(evt);
            }
        });

        salaryBtn.setText("View Salary Structure");
        salaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryBtnActionPerformed(evt);
            }
        });

        leaveBtn.setText("Apply for Leave");
        leaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveBtnActionPerformed(evt);
            }
        });

        assignPrjBtn.setText("Assign Project");
        assignPrjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignPrjBtnActionPerformed(evt);
            }
        });

        viewProjBtn.setText("View Projects");
        viewProjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProjBtnActionPerformed(evt);
            }
        });

        viewProjBtn1.setText("Project Status");
        viewProjBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProjBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl3)
                    .addComponent(lbl5)
                    .addComponent(lbl4)
                    .addComponent(lbl1)
                    .addComponent(lbl2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addrlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(mobilelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emaillbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(approveLeavelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(viewRecBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salaryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leaveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(assignPrjBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewProjBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewProjBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLbl)
                    .addComponent(logoutBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eidlbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(namelbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(emaillbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mobilelbl)
                                        .addGap(14, 14, 14)
                                        .addComponent(addrlbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl4)
                                        .addGap(14, 14, 14)
                                        .addComponent(lbl5)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmp))
                        .addGap(9, 9, 9)
                        .addComponent(updateID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(approveLeavelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assignPrjBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewRecBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salaryBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewProjBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leaveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewProjBtn1)
                        .addGap(61, 61, 61))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approveLeavelblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveLeavelblActionPerformed
        ApproveLeaveFrame approveleave=new ApproveLeaveFrame(eid);
        approveleave.setVisible(true);
    }//GEN-LAST:event_approveLeavelblActionPerformed

    private void addEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpActionPerformed
        AddEmployeeFrame addempPage=null;
        
        int id_index=idComboBox.getSelectedIndex();
        if(id_index==0){//create Employee
            addempPage=new AddEmployeeFrame(eid,0);
            addempPage.setVisible(true);
//            this.setVisible(false);
        }
        else if(id_index==1){//create Manager
            addempPage=new AddEmployeeFrame(eid,1);
            addempPage.setVisible(true);
//            this.setVisible(false);
        }
        else if(id_index==2){//create Executive
            addempPage=new AddEmployeeFrame(eid,2);
            addempPage.setVisible(true);
//            this.setVisible(false);
        }
    }//GEN-LAST:event_addEmpActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        this.dispose();
        LoginPage lp=new LoginPage();
        lp.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void updateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateIDActionPerformed
        UpdateEmpFrame up=new UpdateEmpFrame();
        up.setVisible(true);
    }//GEN-LAST:event_updateIDActionPerformed

    private void viewRecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecBtnActionPerformed
        
        ViewRecords view=new ViewRecords();
        view.setVisible(true);
    }//GEN-LAST:event_viewRecBtnActionPerformed

    private void leaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveBtnActionPerformed
       
        LeaveApplication la=new LeaveApplication(eid);
        la.setVisible(true);
        
        
    }//GEN-LAST:event_leaveBtnActionPerformed

    private void salaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryBtnActionPerformed
        
        SalaryStructure salSt=new SalaryStructure();
        salSt.setVisible(true);
    }//GEN-LAST:event_salaryBtnActionPerformed

    private void assignPrjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignPrjBtnActionPerformed
        
        AssignProjectFrame assignProjectFrame=new AssignProjectFrame();
        assignProjectFrame.setVisible(true);
    }//GEN-LAST:event_assignPrjBtnActionPerformed

    private void viewProjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProjBtnActionPerformed
        
        ViewProjects viewprj = new ViewProjects();
        viewprj.setVisible(true);
        
        
    }//GEN-LAST:event_viewProjBtnActionPerformed

    private void viewProjBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProjBtn1ActionPerformed
        ProjectStatusFrame pj=new ProjectStatusFrame(eid);
        pj.setVisible(true);
    }//GEN-LAST:event_viewProjBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmp;
    private javax.swing.JLabel addrlbl;
    private javax.swing.JButton approveLeavelbl;
    private javax.swing.JButton assignPrjBtn;
    private javax.swing.JLabel eidlbl;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JComboBox<String> idComboBox;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JButton leaveBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel mobilelbl;
    private javax.swing.JLabel namelbl;
    private javax.swing.JButton salaryBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton updateID;
    private javax.swing.JButton viewProjBtn;
    private javax.swing.JButton viewProjBtn1;
    private javax.swing.JButton viewRecBtn;
    // End of variables declaration//GEN-END:variables
}
